name: EC2 deploy from docker

on:
  push:
    branches: ["QA"]
  
  pull_request:
    branches: [main]

jobs:
  login-and-pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
 
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/qa:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/qa:latest

  QA_pipeline:
    if: github.ref == 'refs/heads/QA'
    runs-on: ubuntu-latest
    steps: 
      - name: SSH into QA01 and pull the latest Docker image
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST_QA01 }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY_QA }}
          script: |
            ./docker_setup.sh ${{ secrets.DOCKER_USERNAME }}/qa:latest

      - name: SSH into QA02 and pull the latest Docker image
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST_QA02 }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY_QA }}
          script: |
            ./docker_setup.sh ${{ secrets.DOCKER_USERNAME }}/qa:latest

  PRD_pipeline:
    if: github.event_name == 'pull_request' && github.base_ref == 'main' 
    runs-on: ubuntu-latest
    steps: 
      - name: SSH into PRD01 and pull the latest Docker image
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST_PRD01 }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY_PRD }}
          script: |
            ./docker_setup.sh ${{ secrets.DOCKER_USERNAME }}/qa:latest

      - name: SSH into PRD03 and pull the latest Docker image
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST_PRD02 }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY_PRD }}
          script: |
            ./docker_setup.sh ${{ secrets.DOCKER_USERNAME }}/qa:latest

      - name: SSH into PRD04 and pull the latest Docker image
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST_PRD03 }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY_PRD }}
          script: |
            ./docker_setup.sh ${{ secrets.DOCKER_USERNAME }}/qa:latest

      - name: SSH into PRD02 and pull the latest Docker image
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST_PRD04 }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY_PRD }}
          script: |
            ./docker_setup.sh ${{ secrets.DOCKER_USERNAME }}/qa:latest
